init commit
kruchkou/Task2_REST_Basic pull request #1
Opened 2021-01-19 12:28 UTC by kruchkou

2021-01-19 14:24 UTC, SenPavel requested changes

2021-01-19 14:24 UTC, SenPavel commented on controller/src/main/java/com/epam/esm/controller/advice/GlobalExceptionHandler.java
> +        HttpStatus HTTP_STATUS = HttpStatus.INTERNAL_SERVER_ERROR;
No need to create additional variable to store http status.

2021-01-19 14:24 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/UpdateGiftCertificateSQLBuilder.java
> +        Integer id = giftCertificate.getId();
Please move creation of a variable to where it is used

2021-01-19 14:24 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/UpdateGiftCertificateSQLBuilder.java
> +        Instant lastUpdateDate = giftCertificate.getLastUpdateDate();
Please move creation of a variable to where it is used

2021-01-19 14:24 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    private final TagDAO tagDAO;
Please move static variables after static final variables

2021-01-19 14:24 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    private final static String NO_GIFT_CERTIFICATE_WITH_ID_FOUND = "No certificate with id: %d found";
Please change variable modificators to static final

2021-01-19 14:24 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +    private final static String NOT_FOUND_BY_ID_PARAMETER = "id: %d";
Please change variable modificators to static final

2021-01-19 16:23 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +    private final static String NOT_FOUND_BY_ID_PARAMETER = "id: %d";
Fixed across whole project

2021-01-19 16:24 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    private final static String NO_GIFT_CERTIFICATE_WITH_ID_FOUND = "No certificate with id: %d found";
Fixed across whole project

2021-01-19 16:24 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    private final TagDAO tagDAO;
Haha, classic.
Fixed across whole project

2021-01-19 16:29 UTC, SenPavel approved these changes

2021-01-20 03:49 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/UpdateGiftCertificateSQLBuilder.java
> +        Integer id = giftCertificate.getId();
Fixed across whole project

2021-01-20 03:49 UTC, kruchkou commented on controller/src/main/java/com/epam/esm/controller/advice/GlobalExceptionHandler.java
> +        HttpStatus HTTP_STATUS = HttpStatus.INTERNAL_SERVER_ERROR;
Fixed

2021-01-20 03:49 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/UpdateGiftCertificateSQLBuilder.java
> +        Instant lastUpdateDate = giftCertificate.getLastUpdateDate();
Fixed across whole project

2021-01-21 10:56 UTC, TitenkovEA commented on repository/src/test/java/com/epam/esm/repository/dao/impl/GiftCertificateDAOImplTest.java
> +    public void createGiftCertificate() {
for the future, I advise you to cover negative cases too

2021-01-21 14:20 UTC, kruchkou commented on controller/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +    @Autowired
Annotation was added to clarify that bean is being injected.
Thanks for mentioning, i use latest Spring version, but libs was included manually. Already changed to Maven dependency in latest commit.

2021-01-21 14:45 UTC, kruchkou commented on repository/src/test/java/com/epam/esm/repository/dao/impl/GiftCertificateDAOImplTest.java
> +    public void createGiftCertificate() {
This layer was designed to manipulate with database server. 
Test covers only positive cases because behavior depends on database server configuration.

Business logic is presented in service layer and covered by tests in both positive and negative cases.

2021-01-21 14:49 UTC, TitenkovEA approved these changes

2021-02-08 05:25 UTC, merged