Task3
kruchkou/Task2_REST_Basic pull request #2
Opened 2021-02-08 05:26 UTC by kruchkou

2021-02-09 09:50 UTC, SenPavel requested changes

2021-02-09 09:50 UTC, SenPavel commented on controller/src/main/java/com/epam/esm/controller/TagController.java
> +    @GetMapping("/getMostWidelyUsedTagFromUserWithHighestCostOfAllOrders")
Please rename the endpoint according to REST conventions

2021-02-09 09:50 UTC, SenPavel commented on controller/src/main/java/com/epam/esm/controller/UserController.java
> +    public UserController(UserService userService, com.epam.esm.controller.util.assembler.UserModelAssembler userModelAssembler) {
Remove package from UserModelAssembler

2021-02-09 09:50 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/FilterBuilder.java
> +        int FILTER_VALUE_GROUP_INDEX = 2;
Make these fields class varibles (static final)

2021-02-09 09:50 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/GetGiftCertificateQueryHandler.java
> +public class GetGiftCertificateQueryHandler {
Make this class final, since it is util class

2021-02-09 09:50 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/GiftCertificateFieldUpdater.java
> +public class GiftCertificateFieldUpdater {
Make this class final, since it is util class

2021-02-09 09:50 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/dao/util/SortBuilder.java
> +public class SortBuilder {
Make this class final and create private constructor, since it is util class

2021-02-09 09:50 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/model/util/Page.java
> +    int size = 20;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/model/util/FilterBuilderTest.java
> +class FilterBuilderTest {
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/model/dto/OrderDto.java
> +    Integer price;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/model/dto/UserDto.java
> +    List<UserOrderDto> orderList;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/model/dto/UserInOrderDto.java
> +    String name;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/model/dto/UserOrderDto.java
> +    Integer price;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/model/util/CreateOrderParameter.java
> +    List<@Min(1) Integer> gifts;
specify access modifiers

2021-02-09 09:50 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/util/mapper/EntityDtoOrderMapper.java
> +public class EntityDtoOrderMapper {
Make this class final

2021-02-09 09:50 UTC, SenPavel commented on service/src/test/java/com/epam/esm/service/impl/OrderServiceImplTest.java
> +    }
Remove this method if it is not needed

2021-02-09 09:50 UTC, SenPavel commented on service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +    void getTagsByGiftCertificateID() {
please specify access modifiers

2021-02-09 10:32 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/FilterBuilder.java
> +        int FILTER_VALUE_GROUP_INDEX = 2;
Woops...

2021-02-09 10:33 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GetGiftCertificateQueryHandler.java
> +public class GetGiftCertificateQueryHandler {
Sure

2021-02-09 10:34 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/UserOrderDto.java
> +    Integer price;
Done

2021-02-09 10:36 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/util/mapper/EntityDtoOrderMapper.java
> +public class EntityDtoOrderMapper {
Done

2021-02-09 10:37 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/UserOrderDto.java
> +    Integer price;
Done!

2021-02-09 10:38 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/util/CreateOrderParameter.java
> +    List<@Min(1) Integer> gifts;
Done

2021-02-09 10:38 UTC, kruchkou commented on service/src/test/java/com/epam/esm/service/impl/OrderServiceImplTest.java
> +    }
Done

2021-02-09 10:39 UTC, kruchkou commented on service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +    void getTagsByGiftCertificateID() {
Done

2021-02-09 10:40 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/util/mapper/EntityDtoOrderMapper.java
> +public class EntityDtoOrderMapper {
Done

2021-02-09 10:40 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/UserInOrderDto.java
> +    String name;
Done

2021-02-09 10:40 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/UserDto.java
> +    List<UserOrderDto> orderList;
DOne

2021-02-09 10:40 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/OrderDto.java
> +    Integer price;
Done

2021-02-09 10:41 UTC, kruchkou commented on repository/src/test/java/com/epam/esm/repository/model/util/FilterBuilderTest.java
> +class FilterBuilderTest {
Done

2021-02-09 10:41 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/util/Page.java
> +    int size = 20;
Done

2021-02-09 10:42 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/SortBuilder.java
> +public class SortBuilder {
Done

2021-02-09 10:42 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GiftCertificateFieldUpdater.java
> +public class GiftCertificateFieldUpdater {
Done

2021-02-09 10:43 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GetGiftCertificateQueryHandler.java
> +public class GetGiftCertificateQueryHandler {
Done

2021-02-09 10:44 UTC, kruchkou commented on controller/src/main/java/com/epam/esm/controller/UserController.java
> +    public UserController(UserService userService, com.epam.esm.controller.util.assembler.UserModelAssembler userModelAssembler) {
Done

2021-02-09 10:51 UTC, kruchkou commented on controller/src/main/java/com/epam/esm/controller/TagController.java
> +    @GetMapping("/getMostWidelyUsedTagFromUserWithHighestCostOfAllOrders")
Replaced with orders/highestCost/user/mostUsedTag

2021-02-09 11:06 UTC, SenPavel approved these changes

2021-02-10 18:40 UTC, TitenkovEA requested changes
Overview:
- huge work, good code.
- too much useless blank lines, be careful with this.
- think each time when you want to create one more static util class

2021-02-10 18:40 UTC, TitenkovEA commented on service/src/main/java/com/epam/esm/service/model/dto/UserDto.java
> +    List<UserOrderDto> orderList;
why package-private??
BTW, the comments should be resolved/closed by reviewer

2021-02-11 11:30 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GetGiftCertificateQueryHandler.java
> +     * Returns {@link CriteriaQuery} object with criteria applied
Thanks, really, forgot to update.

2021-02-11 11:32 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GetGiftCertificateQueryHandler.java
> +    public static List<GiftCertificate> handle(EntityManager entityManager,
Yes, actually, i do move picece of code to another class.
That was maded because he is the one that handles GiftCertificateQueryParameter and method is really long.

Thanks for you comment, next time i'll write something more compatible

2021-02-11 11:36 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/FilterBuilder.java
> +
Fixed

2021-02-11 11:44 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/FilterBuilder.java
> +public final class FilterBuilder {
Actually, you right. Factory suits better, that Builder. Fixed.

2021-02-11 12:12 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/dao/util/GiftCertificateFieldUpdater.java
> +public final class GiftCertificateFieldUpdater {
Thanks, that really have sense. 

I replaced classes with a lot of business logic to Spring components.

2021-02-11 12:13 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/entity/Order.java
> +
Fixed

2021-02-11 12:14 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/entity/Order.java
> +
For sure, i didnt do this specially)

2021-02-11 12:14 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/util/GetGiftCertificateQueryParameter.java
> +    @Size(min = 1,max = 200)
Thanks

2021-02-11 12:18 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/util/Page.java
> +    private int page = 1;
Replaced with static def() method

2021-02-11 12:19 UTC, kruchkou commented on service/src/main/java/com/epam/esm/service/model/dto/UserDto.java
> +    List<UserOrderDto> orderList;
fixed... no coments...

2021-02-11 12:29 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/model/entity/GiftCertificate.java
> +import org.hibernate.envers.Audited;
As i understand, hibernate-specific features is about SessionFactory and etc.

@OnDelete and @OnDeleteAction is not required because it shows that in database there are ForeignKey onDelete:Cascade.

Hibernate Envers is additional library for Auditing, that was provided in Materials for this task.

So, i think, that is OK.

2021-02-12 11:44 UTC, TitenkovEA commented
1 - please resolve comments from reviewer only when you got an approval from reviewer!
2 - I do not see a commit with your fixes

2021-02-15 09:24 UTC, TitenkovEA approved these changes

2021-03-10 18:53 UTC, merged