Task4
kruchkou/Task2_REST_Basic pull request #3
Opened 2021-03-11 11:39 UTC by kruchkou

2021-03-15 19:13 UTC, SenPavel requested changes

2021-03-15 19:13 UTC, SenPavel commented on controller/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +    @PreAuthorize("hasRole('ANONYMOUS')")
Is there a difference between @PreAuthorize("hasRole('ANONYMOUS')") and @PreAuthorize("isAnonymous()")?

2021-03-15 19:13 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/OrderRepository.java
> +    List<Order> findByUser_Id(int id);
No need to use underscore

2021-03-16 10:17 UTC, kruchkou commented on controller/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +    @PreAuthorize("hasRole('ANONYMOUS')")
No difference, changed to isAnonymous()

2021-03-16 10:19 UTC, kruchkou commented on repository/src/main/java/com/epam/esm/repository/OrderRepository.java
> +    List<Order> findByUser_Id(int id);
Fixed

2021-03-16 15:26 UTC, SenPavel approved these changes

2021-03-17 12:32 UTC, merged